import Head from 'next/head'
import Image from 'next/image'
import Grid from '../components/grid'
import styles from '../styles/Home.module.css'

import Fab from '@mui/material/Fab';
import AddIcon from '@mui/icons-material/Add';
import Box from '@mui/material/Box';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
<Grid/>
<Box sx={{m:5, position:'inherit'}}>
      <Fab color="primary" aria-label="add">
        <AddIcon />
      </Fab>
      </Box>
      </main>
      
      
    </div>
  )
}
