import Head from 'next/head'
import Image from 'next/image'
import Grid from '../components/grid'
import styles from '../styles/Home.module.css'

import Fab from '@mui/material/Fab';
import AddIcon from '@mui/icons-material/Add';
import Box from '@mui/material/Box';
export default function Home({data}) {
  return (
    < >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


<Grid data={data}/>


      
      
    </>
  )
}
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`http://localhost:8000/person/list`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}
